name: BiliCraftTicketSystem
version: '${project.version}'
author: BigBrother
main: com.bigbrother.bilicraftticketsystem.BiliCraftTicketSystem
api-version: '1.20'
depend: [ Train_Carts, BKCommonLib, Vault ]
softdepend: [ Oraxen ]

permissions:
  bcts.ticket.open:
    description: "使用车票系统权限"
    default: op
  bcts.ticket.uploadbg:
    description: "上传车票背景图权限"
    default: op
  bcts.ticket.adminuploadbg:
    description: "放置showroute控制牌权限"
    default: op
  bcts.ticket.deletebg:
    description: "删除任意车票背景图权限"
    default: op
  bcts.ticket.reload:
    description: "重载配置文件权限"
    default: op
  bcts.ticket.weblogin:
    description: "绑定网页登录资格权限"
    default: true
  bcts.ticket.menuitem:
    description: "添加自定义物品权限"
    default: op
  bcts.ticket.nbt:
    description: "查看和设置nbt的权限"
    default: op
  bcts.ticket.font:
    description: "查看系统支持字体的权限"
    default: op
  bcts.ticket.statistics:
    description: "查看统计数据权限"
    default: op
  bcts.ticket.migrate:
    description: "从旧数据库迁移数据权限"
    default: op
  bcts.ticket.traininfo:
    description: "查看当前所坐列车调试信息权限"
    default: op
  bcts.buildsign.bcspawn:
    description: "放置bcspawn控制牌权限"
    default: op
  bcts.buildsign.platform:
    description: "放置platform站台控制牌权限"
    default: op
  bcts.buildsign.bcswitcher:
    description: "放置bcswitcher道岔控制牌权限"
    default: op
  bcts.buildsign.slowdown:
    description: "放置slowdown减速控制牌权限"
    default: op
  bcts.ticket.getcard:
    description: "获取交通卡权限"
    default: op
  bcts.ticket.editroute:
    description: "游戏内新建/修改线路配置权限"
    default: op
  bcts.ticket.editsystem:
    description: "游戏内新建/修改铁路系统配置权限"
    default: op
  bcts.ticket.debug:
    description: "列车/图调试相关指令"
    default: op
  bcts.railgeo:
    description: "铁轨遍历（railgeo）相关指令权限"
    default: op
  bcts.railgeo.bypasscooldown:
    description: "绕过铁轨遍历全局冷却的权限（绕过执行不刷新冷却）"
    default: op

libraries:
  - com.zaxxer:HikariCP:${hikari.version}
  - org.incendo:cloud-core:${cloud.core.version}
  - org.incendo:cloud-annotations:${cloud.annotations.version}
  - org.incendo:cloud-paper:${cloud.paper.version}
  - org.incendo:cloud-minecraft-extras:${cloud.minecraft.extras.version}
