# 线路配置文件

# 联络线
contact:
  railway-system: "contact" # 特殊id，不存在于railway_system.yml
  line-name: "联络线"
  line-color: "#868686"

# 线路id
pr-cw:
  # 线路基本信息（必填）
  railway-system: "paralon-railway" # 属于哪个铁路系统（必填）
  line-name: "环线（顺时针方向）" # 线路名称
  line-color: "#AA0000"        # 线路标志色
  # bossbar设置
  bossbar-stations: # 车站列表（必填）
    - "Station A"
    - "Station B"
    - "Station C"
    - "Station A"
  # 到站bossbar提示（选填）
  # 可用占位符：
  # 当前站 {curr_station}
  # 线路名 {line_name}
  # 线路16进制颜色（MiniMessage格式） {line_color}
  bossbar-arrival-notice: "&6列车已到达 {line_color}{curr_station}站"
  bossbar-color: "RED"                                     # bossbar颜色（选填）
  # 普通车进出站提示
  # announce 文字同时支持 MiniMessage 标签（如 <red>）与 & 颜色代码，可混用
  # 可用占位符：
  # 当前站 {curr_station}
  # 下一站 {next_station}
  # 线路名 {line_name}
  # 铁路系统 {railway_system}
  # 线路16进制颜色（MiniMessage格式） {line_color}
  notice-arrival: # 进站提示，支持announce, sound...（选填）
    - "sound:noteblock.xxxx,0.56,0.5"
    - "announce:列车即将到达 {line_color}{curr_station}站"
  notice-departure: # 出站提示（选填）
    - "sound:noteblock.xxxx,0.8,0.5"
    - "announce:欢迎乘坐{line_color}{line_name}"
    - "announce:下一站: {line_color}{next_station}"

pr-s1:
  railway-system: "paralon-railway"
  line-name: "S1线"
  line-color: "#AA0000"

  bossbar-stations:
    - "S1-A"
    - "S1-B:RV"
    - "S1-C"
    - "S1-D"
    # 线路id:车站只能存在于最后，含义是：对于普通车来说，经过终点站后，转入pr-s2运行，且下一站是pr-s2的S2-B站。需要更换pr-s2的bossbar（修改列车属性lineID）
    - "pr-s2:S2-B"
  bossbar-arrival-notice: "&6列车已到达 {line_color}{curr_station}站"
  bossbar-color: "RED"

  notice-arrival:
    - "sound:noteblock.xxxx,0.56,0.5"
    - "announce:列车即将到达 {line_color}{curr_station}站"
  notice-departure:
    - "sound:noteblock.xxxx,0.8,0.5"
    - "announce:欢迎乘坐{line_color}{line_name}"
    - "announce:下一站: {line_color}{next_station}"

pr-s2:
  railway-system: "paralon-railway"
  line-name: "S2线"
  line-color: "#AA0000"

  bossbar-stations:
    - "S2-A"
    - "S2-B"
    - "S2-C"
  bossbar-arrival-notice: "&6列车已到达 {line_color}{curr_station}站"
  bossbar-color: "RED"

  notice-arrival:
    - "sound:noteblock.xxxx,0.56,0.5"
    - "announce:列车即将到达 {line_color}{curr_station}站"
  notice-departure:
    - "sound:noteblock.xxxx,0.8,0.5"
    - "announce:欢迎乘坐{line_color}{line_name}"
    - "announce:下一站: {line_color}{next_station}"
