name: BiliCraftTicketSystem
version: '${project.version}'
author: BigBrother
main: com.bigbrother.bilicraftticketsystem.BiliCraftTicketSystem
api-version: '1.20'
depend: [ Train_Carts, BKCommonLib, Vault ]
softdepend:
  - CoreProtect

commands:
  ticket:
    description: 帕拉伦国有铁路车票系统指令
    aliases: [ ticket ]

permissions:
  bcts.ticket.open:
    description: "使用车票系统权限"
    default: op
  bcts.ticket.uploadbg:
    description: "上传车票背景图权限"
    default: op
  bcts.ticket.adminuploadbg:
    description: "放置showroute控制牌权限"
    default: op
  bcts.ticket.deletebg:
    description: "删除任意车票背景图权限"
    default: op
  bcts.ticket.reload:
    description: "重载配置文件权限"
    default: op
  bcts.ticket.menuitem:
    description: "添加自定义物品权限"
    default: op
  bcts.ticket.nbt:
    description: "查看和设置nbt的权限"
    default: op
  bcts.ticket.font:
    description: "查看系统支持字体的权限"
    default: op
  bcts.ticket.statistics:
    description: "查看统计数据权限"
    default: op
  bcts.ticket.co:
    description: "co数据导入权限"
    default: op
  bcts.buildsign.bcspawn:
    description: "放置bcspawn控制牌权限"
    default: op
  bcts.buildsign.showroute:
    description: "放置showroute控制牌权限"
    default: op

libraries:
  - com.zaxxer:HikariCP:5.0.1
