---
config:
  layout: elk
---
graph TD;
    %% ------------------------- 环线铁路-外环方向 -------------------------
    永望堡站-环线铁路-外环方向-ef1==>|2.12|巨龙峡湾站-环线铁路-外环方向-df;
    巨龙峡湾站-环线铁路-外环方向-df==>|3.57|-环线铁路-外环方向-ff;
    -环线铁路-外环方向-ff==>|2.89|东海望站-环线铁路-外环方向-eo1;
    东海望站-环线铁路-外环方向-eo1==>|0.94|-环线铁路-外环方向-pp;
    -环线铁路-外环方向-pp==>|2.55|世界树原野站-环线铁路-外环方向-yp1;
    世界树原野站-环线铁路-外环方向-yp1==>|1.94|秋华町站-环线铁路-外环方向-ac;
    秋华町站-环线铁路-外环方向-ac==>|2.64|贸易海岸站-环线铁路-外环方向-tc;
    贸易海岸站-环线铁路-外环方向-tc==>|1.82|西州湾站-环线铁路-外环方向-xzw;
    西州湾站-环线铁路-外环方向-xzw==>|3.35|翡翠岛站-环线铁路-外环方向-ei;
    翡翠岛站-环线铁路-外环方向-ei==>|4.29|黄昏岛站-环线铁路-外环方向-ti;
    黄昏岛站-环线铁路-外环方向-ti==>|1.88|匕首半岛站-环线铁路-外环方向-dp;
    匕首半岛站-环线铁路-外环方向-dp==>|8.25|银月岛站-环线铁路-外环方向-si;
    银月岛站-环线铁路-外环方向-si==>|0.73|冬幕公园站-环线铁路-外环方向-wp;
    冬幕公园站-环线铁路-外环方向-wp==>|2.21|新赫洛堡站-环线铁路-外环方向-nh;
    新赫洛堡站-环线铁路-外环方向-nh==>|1.51|长岛站-环线铁路-外环方向-li;
    长岛站-环线铁路-外环方向-li==>|4.45|大绿龙岛站-环线铁路-外环方向-ggi;
    大绿龙岛站-环线铁路-外环方向-ggi==>|2.07|龙爪半岛站-环线铁路-外环方向-dcp;
    龙爪半岛站-环线铁路-外环方向-dcp==>|1.44|鹅城站-环线铁路-外环方向-ce;
    鹅城站-环线铁路-外环方向-ce==>|4.07|诺亚站-环线铁路-外环方向-no;
    诺亚站-环线铁路-外环方向-no==>|3.05|风雪峡湾站-环线铁路-外环方向-sf;
    风雪峡湾站-环线铁路-外环方向-sf==>|1.09|-环线铁路-外环方向-scv;
    -环线铁路-外环方向-scv==>|2.16|-环线铁路-外环方向-vr;
    -环线铁路-外环方向-vr==>|4.47|霜湖谷站-环线铁路-外环方向-fv1;
    霜湖谷站-环线铁路-外环方向-fv1==>|2.36|-环线铁路-外环方向-sv;
    -环线铁路-外环方向-sv==>|3.93|永望堡站-环线铁路-外环方向-ef1;

    %% ------------------------- 环线铁路-内环方向 -------------------------
    巨龙峡湾站-环线铁路-内环方向-df==>|2.12|永望堡站-环线铁路-内环方向-ef1;
    -环线铁路-内环方向-ff==>|3.57|巨龙峡湾站-环线铁路-内环方向-df;
    东海望站-环线铁路-内环方向-eo1==>|2.89|-环线铁路-内环方向-ff;
    -环线铁路-内环方向-pp==>|0.94|东海望站-环线铁路-内环方向-eo1;
    世界树原野站-环线铁路-内环方向-yp1==>|2.55|-环线铁路-内环方向-pp;
    秋华町站-环线铁路-内环方向-ac==>|1.94|世界树原野站-环线铁路-内环方向-yp1;
    贸易海岸站-环线铁路-内环方向-tc==>|2.64|秋华町站-环线铁路-内环方向-ac;
    西州湾站-环线铁路-内环方向-xzw==>|1.82|贸易海岸站-环线铁路-内环方向-tc;
    翡翠岛站-环线铁路-内环方向-ei==>|3.35|西州湾站-环线铁路-内环方向-xzw;
    黄昏岛站-环线铁路-内环方向-ti==>|4.29|翡翠岛站-环线铁路-内环方向-ei;
    匕首半岛站-环线铁路-内环方向-dp==>|1.88|黄昏岛站-环线铁路-内环方向-ti;
    银月岛站-环线铁路-内环方向-si==>|8.25|匕首半岛站-环线铁路-内环方向-dp;
    冬幕公园站-环线铁路-内环方向-wp==>|0.73|银月岛站-环线铁路-内环方向-si;
    新赫洛堡站-环线铁路-内环方向-nh==>|2.21|冬幕公园站-环线铁路-内环方向-wp;
    长岛站-环线铁路-内环方向-li==>|1.51|新赫洛堡站-环线铁路-内环方向-nh;
    大绿龙岛站-环线铁路-内环方向-ggi==>|4.45|长岛站-环线铁路-内环方向-li;
    龙爪半岛站-环线铁路-内环方向-dcp==>|2.07|大绿龙岛站-环线铁路-内环方向-ggi;
    鹅城站-环线铁路-内环方向-ce==>|1.44|龙爪半岛站-环线铁路-内环方向-dcp;
    诺亚站-环线铁路-内环方向-no==>|4.07|鹅城站-环线铁路-内环方向-ce;
    风雪峡湾站-环线铁路-内环方向-sf==>|3.05|诺亚站-环线铁路-内环方向-no;
    -环线铁路-内环方向-scv==>|1.09|风雪峡湾站-环线铁路-内环方向-sf;
    -环线铁路-内环方向-vr==>|2.16|-环线铁路-内环方向-scv;
    霜湖谷站-环线铁路-内环方向-fv1==>|4.47|-环线铁路-内环方向-vr;
    -环线铁路-内环方向-sv==>|2.36|霜湖谷站-环线铁路-内环方向-fv1;
    永望堡站-环线铁路-内环方向-ef1==>|3.93|-环线铁路-内环方向-sv;

    %% ------------------------- 芙德铁路-世界树原野方向 -------------------------
    鹅城站-芙德铁路-世界树原野方向-celp2df==>|1.89|暖风河谷站-芙德铁路-世界树原野方向-wv;
    暖风河谷站-芙德铁路-世界树原野方向-wv==>|1.50|结束乐队开发区站-芙德铁路-世界树原野方向-kz;
    结束乐队开发区站-芙德铁路-世界树原野方向-kz==>|1.02|赤脊湾站-芙德铁路-世界树原野方向-rb;
    赤脊湾站-芙德铁路-世界树原野方向-rb==>|1.74|春风平原站-芙德铁路-世界树原野方向-sb;
    春风平原站-芙德铁路-世界树原野方向-sb==>|3.19|丰饶台地西站-芙德铁路-世界树原野方向-fpw;
    丰饶台地西站-芙德铁路-世界树原野方向-fpw==>|0.83|丰饶台地站-芙德铁路-世界树原野方向-fp1;
    丰饶台地站-芙德铁路-世界树原野方向-fp1==>|3.11|德芙站-芙德铁路-世界树原野方向-do;
    德芙站-芙德铁路-世界树原野方向-do==>|1.93|恶土站-芙德铁路-世界树原野方向-bl;
    恶土站-芙德铁路-世界树原野方向-bl==>|1.44|世界树原野站-芙德铁路-世界树原野方向-yp2;
    大绿龙岛站-环线铁路-外环方向-ggi==>|0.00|-芙德铁路-世界树原野方向-ggilp2dfz;
    -芙德铁路-世界树原野方向-ggilp2dfz==>|1.73|龙颚岛站-芙德铁路-世界树原野方向-dji;
    龙颚岛站-芙德铁路-世界树原野方向-dji==>|2.45|赤脊湾站-芙德铁路-世界树原野方向-rb;

    %% ------------------------- 芙德铁路-鹅城/大绿龙岛方向 -------------------------
    暖风河谷站-芙德铁路-鹅城方向-wv==>|1.89|鹅城站-芙德铁路-鹅城方向-celp2df;
    结束乐队开发区站-芙德铁路-鹅城方向-kz==>|1.50|暖风河谷站-芙德铁路-鹅城方向-wv;
    赤脊湾站-芙德铁路-鹅城方向-rb==>|1.02|结束乐队开发区站-芙德铁路-鹅城方向-kz;
    春风平原站-芙德铁路-鹅城方向-sb==>|1.74|赤脊湾站-芙德铁路-大绿龙岛方向-rb2;
    赤脊湾站-芙德铁路-大绿龙岛方向-rb2==>|2.45|龙颚岛站-芙德铁路-大绿龙岛方向-dji;
    龙颚岛站-芙德铁路-大绿龙岛方向-dji==>|1.73|大绿龙岛站-环线铁路-内环方向-ggi;
    春风平原站-芙德铁路-鹅城方向-sb==>|1.74|赤脊湾站-芙德铁路-鹅城方向-rb;
    丰饶台地西站-芙德铁路-鹅城方向-fpw==>|3.19|春风平原站-芙德铁路-鹅城方向-sb;
    丰饶台地站-芙德铁路-鹅城方向-fp1==>|0.83|丰饶台地西站-芙德铁路-鹅城方向-fpw;
    德芙站-芙德铁路-鹅城方向-do==>|3.11|丰饶台地站-芙德铁路-鹅城方向-fp1;
    恶土站-芙德铁路-鹅城方向-bl==>|1.93|德芙站-芙德铁路-鹅城方向-do;
    世界树原野站-芙德铁路-鹅城方向-yp2==>|1.44|恶土站-芙德铁路-鹅城方向-bl;

    %% ------------------------- 普朗铁路-永望堡方向 -------------------------
    黄昏岛站-普朗铁路-永望堡方向-ti2==>|1.91|-普朗铁路-永望堡方向-cf;
    -普朗铁路-永望堡方向-cf==>|2.34|帝王谷站-普朗铁路-永望堡方向-ev;
    帝王谷站-普朗铁路-永望堡方向-ev==>|2.72|-普朗铁路-永望堡方向-ap;
    -普朗铁路-永望堡方向-ap==>|3.09|-普朗铁路-永望堡方向-rr;
    -普朗铁路-永望堡方向-rr==>|1.84|丰饶台地站-普朗铁路-永望堡方向-fp2;
    丰饶台地站-普朗铁路-永望堡方向-fp2==>|1.36|丰饶台地北站-普朗铁路-永望堡方向-fpn;
    丰饶台地北站-普朗铁路-永望堡方向-fpn==>|2.80|新特拉姆站-普朗铁路-永望堡方向-nt;
    新特拉姆站-普朗铁路-永望堡方向-nt==>|1.75|-普朗铁路-永望堡方向-bt;
    -普朗铁路-永望堡方向-bt==>|2.90|-普朗铁路-永望堡方向-sff;
    -普朗铁路-永望堡方向-sff==>|1.84|冰晶湖站-普朗铁路-永望堡方向-fcl;
    冰晶湖站-普朗铁路-永望堡方向-fcl==>|2.91|永望堡站-普朗铁路-世界边缘山脉方向-ef2;

    %% ------------------------- 普朗铁路-黄昏岛方向 -------------------------
    永望堡站-普朗铁路-黄昏岛方向-ef2==>|2.91|冰晶湖站-普朗铁路-黄昏岛方向-fcl;
    冰晶湖站-普朗铁路-黄昏岛方向-fcl==>|1.84|-普朗铁路-黄昏岛方向-sff;
    -普朗铁路-黄昏岛方向-sff==>|2.90|-普朗铁路-黄昏岛方向-bt;
    -普朗铁路-黄昏岛方向-bt==>|1.75|新特拉姆站-普朗铁路-黄昏岛方向-nt;
    新特拉姆站-普朗铁路-黄昏岛方向-nt==>|2.80|丰饶台地北站-普朗铁路-黄昏岛方向-fpn;
    丰饶台地北站-普朗铁路-黄昏岛方向-fpn==>|1.36|丰饶台地站-普朗铁路-黄昏岛方向-fp2;
    丰饶台地站-普朗铁路-黄昏岛方向-fp2==>|1.84|-普朗铁路-黄昏岛方向-rr;
    -普朗铁路-黄昏岛方向-rr==>|3.09|-普朗铁路-黄昏岛方向-ap;
    -普朗铁路-黄昏岛方向-ap==>|2.72|帝王谷站-普朗铁路-黄昏岛方向-ev;
    帝王谷站-普朗铁路-黄昏岛方向-ev==>|2.34|-普朗铁路-黄昏岛方向-cf;
    -普朗铁路-黄昏岛方向-cf==>|1.91|黄昏岛站-普朗铁路-黄昏岛方向-ti2;

    %% ------------------------- 赫蒙铁路-霜湖谷方向 -------------------------
    新赫洛堡站-赫蒙铁路-霜湖谷方向-nh2==>|2.90|-赫蒙铁路-霜湖谷方向-sti;
    -赫蒙铁路-霜湖谷方向-sti==>|5.58|泽地站-赫蒙铁路-霜湖谷方向-spi;
    泽地站-赫蒙铁路-霜湖谷方向-spi==>|1.97|春风平原站-赫蒙铁路-霜湖谷方向-sb2;
    春风平原站-赫蒙铁路-霜湖谷方向-sb2==>|3.29|金色平原站-赫蒙铁路-霜湖谷方向-gp;
    金色平原站-赫蒙铁路-霜湖谷方向-gp==>|1.14|-赫蒙铁路-霜湖谷方向-ew;
    -赫蒙铁路-霜湖谷方向-ew==>|1.32|秋林谷站-赫蒙铁路-霜湖谷方向-av;
    秋林谷站-赫蒙铁路-霜湖谷方向-av==>|1.76|冬泉谷站-赫蒙铁路-霜湖谷方向-wsv1;
    冬泉谷站-赫蒙铁路-霜湖谷方向-wsv1==>|1.92|-赫蒙铁路-霜湖谷方向-cm;
    -赫蒙铁路-霜湖谷方向-cm==>|2.51|霜湖谷站-赫蒙铁路-霜湖谷方向-fv2;

    %% ------------------------- 赫蒙铁路-新赫洛堡方向 -------------------------
    -赫蒙铁路-新赫洛堡方向-sti==>|2.90|新赫洛堡站-赫蒙铁路-新赫洛堡方向-nh2;
    泽地站-赫蒙铁路-新赫洛堡方向-spi==>|5.58|-赫蒙铁路-新赫洛堡方向-sti;
    春风平原站-赫蒙铁路-新赫洛堡方向-sb2==>|1.97|泽地站-赫蒙铁路-新赫洛堡方向-spi;
    金色平原站-赫蒙铁路-新赫洛堡方向-gp==>|3.29|春风平原站-赫蒙铁路-新赫洛堡方向-sb2;
    -赫蒙铁路-新赫洛堡方向-ew==>|1.14|金色平原站-赫蒙铁路-新赫洛堡方向-gp;
    秋林谷站-赫蒙铁路-新赫洛堡方向-av==>|1.32|-赫蒙铁路-新赫洛堡方向-ew;
    冬泉谷站-赫蒙铁路-新赫洛堡方向-wsv1==>|1.76|秋林谷站-赫蒙铁路-新赫洛堡方向-av;
    -赫蒙铁路-新赫洛堡方向-cm==>|1.92|冬泉谷站-赫蒙铁路-新赫洛堡方向-wsv1;
    霜湖谷站-赫蒙铁路-新赫洛堡方向-fv2==>|2.51|-赫蒙铁路-新赫洛堡方向-cm;

    %% ------------------------- 蒙德铁路-诺亚方向 -------------------------
    冬泉谷站-蒙德铁路-诺亚方向-wsv2==>|2.55|诺亚站-蒙德铁路-诺亚方向-no2;

    %% ------------------------- 蒙德铁路-东海望方向 -------------------------
    诺亚站-蒙德铁路-东海望方向-no2==>|2.55|冬泉谷站-蒙德铁路-东海望方向-wsv2;

    %% ------------------------- 联络线 -------------------------
    %% 芙德<-->鹅城<-->环线
    鹅城站-芙德铁路-鹅城方向-celp2df-.->|4.07|诺亚站-环线铁路-外环方向-no;
    诺亚站-环线铁路-内环方向-no-.->|4.07|鹅城站-芙德铁路-世界树原野方向-celp2df;
    %% 丰饶台地 芙德<-->普朗
    丰饶台地西站-芙德铁路-世界树原野方向-fpw-.->|0.83|丰饶台地站-普朗铁路-永望堡方向-fp2;
    丰饶台地北站-普朗铁路-黄昏岛方向-fpn-.->|1.36|丰饶台地站-芙德铁路-鹅城方向-fp1;
    %% 世界树原野 环线<-->芙德
    世界树原野站-芙德铁路-世界树原野方向-yp2-.->|0.00|世界树原野站-环线铁路-外环方向-yp1;
    秋华町站-环线铁路-内环方向-ac-.->|1.94|世界树原野站-芙德铁路-鹅城方向-yp2;
    %% 恶土<-->环线
    -环线铁路-外环方向-pp-.->|3.65|-/-/-yplp2df;
    -/-/-yplp2df-.->|0.00|恶土站-芙德铁路-鹅城方向-bl;
    -/-/-ypdf2lp-.->|3.65|-环线铁路-内环方向-pp;
    恶土站-芙德铁路-世界树原野方向-bl-.->|0.00|-/-/-ypdf2lp;
    %% 春风平原 芙德<-->赫蒙
    春风平原站-赫蒙铁路-新赫洛堡方向-sb2-.->|0.00|春风平原站-芙德铁路-世界树原野方向-sb;
    丰饶台地西站-芙德铁路-鹅城方向-fpw-.->|3.19|春风平原站-赫蒙铁路-霜湖谷方向-sb2;
    春风平原站-芙德铁路-世界树原野方向-sb-.->|0.00|-/-/-sbdf2hm;
    -/-/-sbdf2hm-.->|1.97|泽地站-赫蒙铁路-新赫洛堡方向-spi;
    泽地站-赫蒙铁路-霜湖谷方向-spi-.->|1.97|-/-/-sbhm2df;
    -/-/-sbhm2df-.->|0.00|春风平原站-芙德铁路-鹅城方向-sb;
    %% 普朗<-->黄昏岛<-->环线
    黄昏岛站-普朗铁路-黄昏岛方向-ti2-.->|1.88|匕首半岛站-环线铁路-外环方向-dp;
    匕首半岛站-环线铁路-内环方向-dp-.->|1.88|黄昏岛站-普朗铁路-永望堡方向-ti2;
    %% 蒙德<-->诺亚<-->环线
    风雪峡湾站-环线铁路-内环方向-sf-.->|3.05|诺亚站-蒙德铁路-东海望方向-no2;
    诺亚站-蒙德铁路-诺亚方向-no2-.->|0.00|诺亚站-环线铁路-外环方向-no;
    %% 冬泉谷 蒙德<-->赫蒙
    秋林谷站-赫蒙铁路-霜湖谷方向-av-.->|1.76|冬泉谷站-蒙德铁路-诺亚方向-wsv2;
    诺亚站-蒙德铁路-东海望方向-no2-.->|2.55|冬泉谷站-赫蒙铁路-新赫洛堡方向-wsv1;
    %% 芙德<-->森海环线<-->赫蒙
    春风平原站-芙德铁路-世界树原野方向-sb-.->|0.00|-/-/-sbdf2shlp;
    -/-/-sbdf2shlp-.->|4.10|金色平原站-赫蒙铁路-霜湖谷方向-gp;
    金色平原站-赫蒙铁路-新赫洛堡方向-gp-.->|4.10|-/-/-sbhm2shlp;
    -/-/-sbhm2shlp-.->|0.00|春风平原站-芙德铁路-鹅城方向-sb;
    %% 芙德<--->普朗
    丰饶台地北站-普朗铁路-黄昏岛方向-fpn-.->|0.00|-/-/-fpnpl2df;
    -/-/-fpnpl2df-.->|3.35|德芙站-芙德铁路-世界树原野方向-do;
    德芙站-芙德铁路-鹅城方向-do-.->|3.35|-/-/-fpndf2pl;
    -/-/-fpndf2pl-.->|0.00|丰饶台地北站-普朗铁路-永望堡方向-fpn;
    %% 永望堡 普朗<-->环线
    -环线铁路-外环方向-sv-.->|0.00|-/-/-eflp2pl;
    -/-/-eflp2pl-.->|5.44|冰晶湖站-普朗铁路-黄昏岛方向-fcl;
    冰晶湖站-普朗铁路-永望堡方向-fcl-.->|5.44|-/-/-efpl2lp;
    -/-/-efpl2lp-.->|0.00|-环线铁路-内环方向-sv;
    %% 霜湖谷 赫蒙<-->环线
    -赫蒙铁路-霜湖谷方向-cm-.->|2.51|霜湖谷站-环线铁路-外环方向-fv1;
    霜湖谷站-环线铁路-内环方向-fv1-.->|0.00|霜湖谷站-赫蒙铁路-新赫洛堡方向-fv2;


    classDef 环线铁路 fill:#FF3030,stroke:#333,stroke-width:2px,color:#000000;
    classDef 芙德铁路 fill:#00CD66,stroke:#333,stroke-width:2px,color:#000000;
    classDef 普朗铁路 fill:#FFB90F,stroke:#333,stroke-width:2px,color:#000000;
    classDef 赫蒙铁路 fill:#0A5CDF,stroke:#333,stroke-width:2px,color:#000000;
    classDef 蒙德铁路 fill:#00F5FF,stroke:#333,stroke-width:2px,color:#000000;
    class 霜湖谷站-环线铁路-内环方向-fv1,霜湖谷站-环线铁路-外环方向-fv1,风雪峡湾站-环线铁路-外环方向-sf,风雪峡湾站-环线铁路-内环方向-sf,冬幕公园站-环线铁路-内环方向-wp,冬幕公园站-环线铁路-外环方向-wp,东海望站-环线铁路-内环方向-eo1,东海望站-环线铁路-外环方向-eo1,巨龙峡湾站-环线铁路-内环方向-df,巨龙峡湾站-环线铁路-外环方向-df,永望堡站-环线铁路-内环方向-ef1,永望堡站-环线铁路-外环方向-ef1,匕首半岛站-环线铁路-外环方向-dp,贸易海岸站-环线铁路-外环方向-tc,龙爪半岛站-环线铁路-外环方向-dcp,翡翠岛站-环线铁路-外环方向-ei,秋华町站-环线铁路-外环方向-ac,鹅城站-环线铁路-外环方向-ce,诺亚站-环线铁路-外环方向-no,西州湾站-环线铁路-外环方向-xzw,黄昏岛站-环线铁路-外环方向-ti,银月岛站-环线铁路-外环方向-si,长岛站-环线铁路-外环方向-li,新赫洛堡站-环线铁路-外环方向-nh,大绿龙岛站-环线铁路-外环方向-ggi,银月岛站-环线铁路-内环方向-si,翡翠岛站-环线铁路-内环方向-ei,长岛站-环线铁路-内环方向-li,西州湾站-环线铁路-内环方向-xzw,秋华町站-环线铁路-内环方向-ac,匕首半岛站-环线铁路-内环方向-dp,贸易海岸站-环线铁路-内环方向-tc,鹅城站-环线铁路-内环方向-ce,诺亚站-环线铁路-内环方向-no,龙爪半岛站-环线铁路-内环方向-dcp,黄昏岛站-环线铁路-内环方向-ti,新赫洛堡站-环线铁路-内环方向-nh,大绿龙岛站-环线铁路-内环方向-ggi,世界树原野站-环线铁路-内环方向-yp1,世界树原野站-环线铁路-外环方向-yp1 环线铁路;
    class 赤脊湾站-芙德铁路-大绿龙岛方向-rb2,龙颚岛站-芙德铁路-大绿龙岛方向-dji,龙颚岛站-芙德铁路-世界树原野方向-dji,结束乐队开发区站-芙德铁路-鹅城方向-kz,结束乐队开发区站-芙德铁路-世界树原野方向-kz,德芙站-芙德铁路-鹅城方向-do,暖风河谷站-芙德铁路-鹅城方向-wv,赤脊湾站-芙德铁路-鹅城方向-rb,春风平原站-芙德铁路-鹅城方向-sb,丰饶台地西站-芙德铁路-世界树原野方向-fpw,春风平原站-芙德铁路-世界树原野方向-sb,暖风河谷站-芙德铁路-世界树原野方向-wv,丰饶台地站-芙德铁路-鹅城方向-fp1,丰饶台地站-芙德铁路-世界树原野方向-fp1,鹅城站-芙德铁路-鹅城方向-celp2df,丰饶台地西站-芙德铁路-鹅城方向-fpw,德芙站-芙德铁路-世界树原野方向-do,赤脊湾站-芙德铁路-世界树原野方向-rb,鹅城站-芙德铁路-世界树原野方向-celp2df,恶土站-芙德铁路-世界树原野方向-bl,世界树原野站-芙德铁路-世界树原野方向-yp2,恶土站-芙德铁路-鹅城方向-bl,世界树原野站-芙德铁路-鹅城方向-yp2 芙德铁路;
    class 冰晶湖站-普朗铁路-黄昏岛方向-fcl,冰晶湖站-普朗铁路-永望堡方向-fcl,永望堡站-普朗铁路-世界边缘山脉方向-ef2,永望堡站-普朗铁路-黄昏岛方向-ef2,黄昏岛站-普朗铁路-黄昏岛方向-ti2,帝王谷站-普朗铁路-黄昏岛方向-ev,帝王谷站-普朗铁路-永望堡方向-ev,黄昏岛站-普朗铁路-永望堡方向-ti2,丰饶台地北站-普朗铁路-永望堡方向-fpn,丰饶台地北站-普朗铁路-黄昏岛方向-fpn,丰饶台地站-普朗铁路-永望堡方向-fp2,新特拉姆站-普朗铁路-永望堡方向-nt,新特拉姆站-普朗铁路-黄昏岛方向-nt,丰饶台地站-普朗铁路-黄昏岛方向-fp2 普朗铁路;
    class 霜湖谷站-赫蒙铁路-新赫洛堡方向-fv2,霜湖谷站-赫蒙铁路-霜湖谷方向-fv2,秋林谷站-赫蒙铁路-霜湖谷方向-av,秋林谷站-赫蒙铁路-新赫洛堡方向-av,冬泉谷站-赫蒙铁路-霜湖谷方向-wsv1,冬泉谷站-赫蒙铁路-新赫洛堡方向-wsv1,泽地站-赫蒙铁路-新赫洛堡方向-spi,泽地站-赫蒙铁路-霜湖谷方向-spi,金色平原站-赫蒙铁路-新赫洛堡方向-gp,金色平原站-赫蒙铁路-霜湖谷方向-gp,春风平原站-赫蒙铁路-新赫洛堡方向-sb2,新赫洛堡站-赫蒙铁路-新赫洛堡方向-nh2,新赫洛堡站-赫蒙铁路-霜湖谷方向-nh2,春风平原站-赫蒙铁路-霜湖谷方向-sb2 赫蒙铁路;
    class 诺亚站-蒙德铁路-东海望方向-no2,冬泉谷站-蒙德铁路-东海望方向-wsv2,冬泉谷站-蒙德铁路-诺亚方向-wsv2,诺亚站-蒙德铁路-诺亚方向-no2 蒙德铁路
