---
config:
  layout: elk
  id: f97a7388-2203-4cbb-a0e1-2ec7f9f9ce00
---

graph TD;
%% ------------------------- 环线铁路-外环方向 -------------------------
    永望堡站-环线铁路-外环方向-ef1==>|2.12|巨龙峡湾站-环线铁路-外环方向-df;
    巨龙峡湾站-环线铁路-外环方向-df==>|3.57|-环线铁路-外环方向-ff;
    -环线铁路-外环方向-ff==>|2.89|东海望站-环线铁路-外环方向-eo1;
    东海望站-环线铁路-外环方向-eo1==>|0.94|天堂群峰站-环线铁路-外环方向-pp;
    天堂群峰站-环线铁路-外环方向-pp==>|2.55|世界树原野站-环线铁路-外环方向-yp1;
    世界树原野站-环线铁路-外环方向-yp1==>|1.94|秋华町站-环线铁路-外环方向-ac;
    秋华町站-环线铁路-外环方向-ac==>|2.64|贸易海岸站-环线铁路-外环方向-tc;
    贸易海岸站-环线铁路-外环方向-tc==>|1.82|西州湾站-环线铁路-外环方向-xzw;
    西州湾站-环线铁路-外环方向-xzw==>|3.35|翡翠岛站-环线铁路-外环方向-ei;
    翡翠岛站-环线铁路-外环方向-ei==>|4.29|黄昏岛站-环线铁路-外环方向-ti;
    黄昏岛站-环线铁路-外环方向-ti==>|1.88|匕首半岛站-环线铁路-外环方向-dp;
    匕首半岛站-环线铁路-外环方向-dp==>|8.25|银月岛站-环线铁路-外环方向-si;
    银月岛站-环线铁路-外环方向-si==>|0.73|冬幕公园站-环线铁路-外环方向-wp;
    冬幕公园站-环线铁路-外环方向-wp==>|2.21|新赫洛堡站-环线铁路-外环方向-nh;
    新赫洛堡站-环线铁路-外环方向-nh==>|1.51|长岛站-环线铁路-外环方向-li;
    长岛站-环线铁路-外环方向-li==>|4.45|大绿龙岛站-环线铁路-外环方向-ggi;
    大绿龙岛站-环线铁路-外环方向-ggi==>|2.07|龙爪半岛站-环线铁路-外环方向-dcp;
    龙爪半岛站-环线铁路-外环方向-dcp==>|1.44|鹅城站-环线铁路-外环方向-ce;
    鹅城站-环线铁路-外环方向-ce==>|4.07|诺亚站-环线铁路-外环方向-no;
    诺亚站-环线铁路-外环方向-no==>|3.05|风雪峡湾站-环线铁路-外环方向-sf;
    风雪峡湾站-环线铁路-外环方向-sf==>|1.09|-环线铁路-外环方向-scv;
    -环线铁路-外环方向-scv==>|2.16|苍原岭站-环线铁路-外环方向-vr;
    苍原岭站-环线铁路-外环方向-vr==>|4.47|霜湖谷站-环线铁路-外环方向-fv1;
    霜湖谷站-环线铁路-外环方向-fv1==>|2.36|-环线铁路-外环方向-sv;
    -环线铁路-外环方向-sv==>|3.93|永望堡站-环线铁路-外环方向-ef1;

%% ------------------------- 环线铁路-内环方向 -------------------------
    巨龙峡湾站-环线铁路-内环方向-df==>|2.12|永望堡站-环线铁路-内环方向-ef1;
    -环线铁路-内环方向-ff==>|3.57|巨龙峡湾站-环线铁路-内环方向-df;
    东海望站-环线铁路-内环方向-eo1==>|2.89|-环线铁路-内环方向-ff;
    天堂群峰站-环线铁路-内环方向-pp==>|0.94|东海望站-环线铁路-内环方向-eo1;
    世界树原野站-环线铁路-内环方向-yp1==>|2.55|天堂群峰站-环线铁路-内环方向-pp;
    秋华町站-环线铁路-内环方向-ac==>|1.94|世界树原野站-环线铁路-内环方向-yp1;
    贸易海岸站-环线铁路-内环方向-tc==>|2.64|秋华町站-环线铁路-内环方向-ac;
    西州湾站-环线铁路-内环方向-xzw==>|1.82|贸易海岸站-环线铁路-内环方向-tc;
    翡翠岛站-环线铁路-内环方向-ei==>|3.35|西州湾站-环线铁路-内环方向-xzw;
    黄昏岛站-环线铁路-内环方向-ti==>|4.29|翡翠岛站-环线铁路-内环方向-ei;
    匕首半岛站-环线铁路-内环方向-dp==>|1.88|黄昏岛站-环线铁路-内环方向-ti;
    银月岛站-环线铁路-内环方向-si==>|8.25|匕首半岛站-环线铁路-内环方向-dp;
    冬幕公园站-环线铁路-内环方向-wp==>|0.73|银月岛站-环线铁路-内环方向-si;
    新赫洛堡站-环线铁路-内环方向-nh==>|2.21|冬幕公园站-环线铁路-内环方向-wp;
    长岛站-环线铁路-内环方向-li==>|1.51|新赫洛堡站-环线铁路-内环方向-nh;
    大绿龙岛站-环线铁路-内环方向-ggi==>|4.45|长岛站-环线铁路-内环方向-li;
    龙爪半岛站-环线铁路-内环方向-dcp==>|2.07|大绿龙岛站-环线铁路-内环方向-ggi;
    鹅城站-环线铁路-内环方向-ce==>|1.44|龙爪半岛站-环线铁路-内环方向-dcp;
    诺亚站-环线铁路-内环方向-no==>|4.07|鹅城站-环线铁路-内环方向-ce;
    风雪峡湾站-环线铁路-内环方向-sf==>|3.05|诺亚站-环线铁路-内环方向-no;
    -环线铁路-内环方向-scv==>|1.09|风雪峡湾站-环线铁路-内环方向-sf;
    苍原岭站-环线铁路-内环方向-vr==>|2.16|-环线铁路-内环方向-scv;
    霜湖谷站-环线铁路-内环方向-fv1==>|4.47|苍原岭站-环线铁路-内环方向-vr;
    -环线铁路-内环方向-sv==>|2.36|霜湖谷站-环线铁路-内环方向-fv1;
    永望堡站-环线铁路-内环方向-ef1==>|3.93|-环线铁路-内环方向-sv;

%% ------------------------- 芙德铁路-碧玺岛方向 -------------------------
    鹅城站-芙德铁路-碧玺岛方向-ce2==>|1.89|暖风河谷站-芙德铁路-碧玺岛方向-wv;
    暖风河谷站-芙德铁路-碧玺岛方向-wv==>|1.50|结束乐队开发区站-芙德铁路-碧玺岛方向-kz;
    结束乐队开发区站-芙德铁路-碧玺岛方向-kz==>|1.02|赤脊湾站-芙德铁路-碧玺岛方向-rb;
    赤脊湾站-芙德铁路-碧玺岛方向-rb==>|1.74|春风平原站-芙德铁路-碧玺岛方向-sb;
    春风平原站-芙德铁路-碧玺岛方向-sb==>|3.19|丰饶台地西站-芙德铁路-碧玺岛方向-fpw;
    丰饶台地西站-芙德铁路-碧玺岛方向-fpw==>|0.83|丰饶台地站-芙德铁路-碧玺岛方向-fp1;
    丰饶台地站-芙德铁路-碧玺岛方向-fp1==>|3.11|德芙站-芙德铁路-碧玺岛方向-do;
    德芙站-芙德铁路-碧玺岛方向-do==>|1.93|恶土站-芙德铁路-碧玺岛方向-bl;
    恶土站-芙德铁路-碧玺岛方向-bl==>|1.44|世界树原野站-芙德铁路-碧玺岛方向-yp2;
    世界树原野站-芙德铁路-碧玺岛方向-yp2==>|3.68|碧玺岛站-芙德铁路-碧玺岛方向-bi;

    大绿龙岛站-环线铁路-外环方向-ggi==>|0.00|-芙德铁路-碧玺岛方向-ggilp2dfz;
    -芙德铁路-碧玺岛方向-ggilp2dfz==>|1.73|龙颚岛站-芙德铁路-碧玺岛方向-dji;
    龙颚岛站-芙德铁路-碧玺岛方向-dji==>|2.45|-芙德铁路-碧玺岛方向-rbfdzd2fdd;
    -芙德铁路-碧玺岛方向-rbfdzd2fdd==>|0.00|赤脊湾站-芙德铁路-碧玺岛方向-rb;

    龙爪半岛站-环线铁路-内环方向-dcp==>|0.00|-芙德铁路-碧玺岛方向-fdz2d;
    -芙德铁路-碧玺岛方向-fdz2d==>|1.15|温泉度假村站-芙德铁路-碧玺岛方向-tsr;
    温泉度假村站-芙德铁路-碧玺岛方向-tsr==>|2.96|赤脊湾站-芙德铁路-碧玺岛方向-rb;

%% ------------------------- 芙德铁路-鹅城/大绿龙岛/龙爪半岛方向 -------------------------
    暖风河谷站-芙德铁路-鹅城方向-wv==>|1.89|鹅城站-芙德铁路-鹅城方向-ce2;
    结束乐队开发区站-芙德铁路-鹅城方向-kz==>|1.50|暖风河谷站-芙德铁路-鹅城方向-wv;
    赤脊湾站-芙德铁路-鹅城方向-rb==>|1.02|结束乐队开发区站-芙德铁路-鹅城方向-kz;
    春风平原站-芙德铁路-鹅城方向-sb==>|1.74|赤脊湾站-芙德铁路-鹅城方向-rb;
    丰饶台地西站-芙德铁路-鹅城方向-fpw==>|3.19|春风平原站-芙德铁路-鹅城方向-sb;
    丰饶台地站-芙德铁路-鹅城方向-fp1==>|0.83|丰饶台地西站-芙德铁路-鹅城方向-fpw;
    德芙站-芙德铁路-鹅城方向-do==>|3.11|丰饶台地站-芙德铁路-鹅城方向-fp1;
    恶土站-芙德铁路-鹅城方向-bl==>|1.93|德芙站-芙德铁路-鹅城方向-do;
    世界树原野站-芙德铁路-鹅城方向-yp2==>|1.44|恶土站-芙德铁路-鹅城方向-bl;
    碧玺岛站-芙德铁路-鹅城方向-bi==>|3.68|世界树原野站-芙德铁路-鹅城方向-yp2;

    赤脊湾站-芙德铁路-大绿龙岛方向-rb2==>|2.45|龙颚岛站-芙德铁路-大绿龙岛方向-dji;
    龙颚岛站-芙德铁路-大绿龙岛方向-dji==>|1.73|大绿龙岛站-环线铁路-内环方向-ggi;

    赤脊湾站-芙德铁路-龙爪半岛方向-rb3==>|0.00|-芙德铁路-龙爪半岛方向-rbfdu2fdzu2;
    -芙德铁路-龙爪半岛方向-rbfdu2fdzu2==>|2.96|温泉度假村站-芙德铁路-龙爪半岛方向-tsr;
    温泉度假村站-芙德铁路-龙爪半岛方向-tsr==>|1.15|龙爪半岛站-环线铁路-外环方向-dcp;

%% ------------------------- 普朗铁路-世界边缘山脉方向 -------------------------
    黄昏岛站-普朗铁路-世界边缘山脉方向-ti2==>|1.91|-普朗铁路-世界边缘山脉方向-cf;
    -普朗铁路-世界边缘山脉方向-cf==>|2.34|帝王谷站-普朗铁路-世界边缘山脉方向-ev;
    帝王谷站-普朗铁路-世界边缘山脉方向-ev==>|2.72|金合欢高原站-普朗铁路-世界边缘山脉方向-ap;
    金合欢高原站-普朗铁路-世界边缘山脉方向-ap==>|3.13|红色裂土站-普朗铁路-世界边缘山脉方向-rr;
    红色裂土站-普朗铁路-世界边缘山脉方向-rr==>|1.80|丰饶台地站-普朗铁路-世界边缘山脉方向-fp2;
    丰饶台地站-普朗铁路-世界边缘山脉方向-fp2==>|1.36|丰饶台地北站-普朗铁路-世界边缘山脉方向-fpn;
    丰饶台地北站-普朗铁路-世界边缘山脉方向-fpn==>|2.80|新特拉姆站-普朗铁路-世界边缘山脉方向-nt;
    新特拉姆站-普朗铁路-世界边缘山脉方向-nt==>|1.75|-普朗铁路-世界边缘山脉方向-bt;
    -普朗铁路-世界边缘山脉方向-bt==>|2.90|星陨森林站-普朗铁路-世界边缘山脉方向-sff;
    星陨森林站-普朗铁路-世界边缘山脉方向-sff==>|1.84|冰晶湖站-普朗铁路-世界边缘山脉方向-fcl;
    冰晶湖站-普朗铁路-世界边缘山脉方向-fcl==>|2.91|永望堡站-普朗铁路-世界边缘山脉方向-ef2;
    永望堡站-普朗铁路-世界边缘山脉方向-ef2==>|2.59|不可视境界站-普朗铁路-世界边缘山脉方向-bw;
    不可视境界站-普朗铁路-世界边缘山脉方向-bw==>|2.68|世界边缘山脉站-普朗铁路-世界边缘山脉方向-em;

    贸易海岸站-普朗铁路-世界边缘山脉方向-tc2==>|2.93|明艳谷站-普朗铁路-世界边缘山脉方向-rv;
    明艳谷站-普朗铁路-世界边缘山脉方向-rv==>|3.78|金合欢高原站-普朗铁路-世界边缘山脉方向-ap;

    帝王谷站-普朗铁路-世界边缘山脉方向-ev==>|0.00|-/-/-evpld2plzd;
    -/-/-evpld2plzd==>|2.40|明艳谷站-普朗铁路-贸易海岸方向-rv;

%% ------------------------- 普朗铁路-黄昏岛方向 -------------------------
    世界边缘山脉站-普朗铁路-黄昏岛方向-em==>|2.68|不可视境界站-普朗铁路-黄昏岛方向-bw;
    不可视境界站-普朗铁路-黄昏岛方向-bw==>|2.59|永望堡站-普朗铁路-黄昏岛方向-ef2;
    永望堡站-普朗铁路-黄昏岛方向-ef2==>|2.91|冰晶湖站-普朗铁路-黄昏岛方向-fcl;
    冰晶湖站-普朗铁路-黄昏岛方向-fcl==>|1.84|星陨森林站-普朗铁路-黄昏岛方向-sff;
    星陨森林站-普朗铁路-黄昏岛方向-sff==>|2.90|-普朗铁路-黄昏岛方向-bt;
    -普朗铁路-黄昏岛方向-bt==>|1.75|新特拉姆站-普朗铁路-黄昏岛方向-nt;
    新特拉姆站-普朗铁路-黄昏岛方向-nt==>|2.80|丰饶台地北站-普朗铁路-黄昏岛方向-fpn;
    丰饶台地北站-普朗铁路-黄昏岛方向-fpn==>|1.36|丰饶台地站-普朗铁路-黄昏岛方向-fp2;
    丰饶台地站-普朗铁路-黄昏岛方向-fp2==>|1.80|红色裂土站-普朗铁路-黄昏岛方向-rr;
    红色裂土站-普朗铁路-黄昏岛方向-rr==>|3.13|金合欢高原站-普朗铁路-黄昏岛方向-ap;
    金合欢高原站-普朗铁路-黄昏岛方向-ap==>|2.72|帝王谷站-普朗铁路-黄昏岛方向-ev;
    帝王谷站-普朗铁路-黄昏岛方向-ev==>|2.34|-普朗铁路-黄昏岛方向-cf;
    -普朗铁路-黄昏岛方向-cf==>|1.91|黄昏岛站-普朗铁路-黄昏岛方向-ti2;

    金合欢高原站-普朗铁路-黄昏岛方向-ap==>|0.00|-/-/-evplu2plzd;
    -/-/-evplu2plzd==>|3.78|明艳谷站-普朗铁路-贸易海岸方向-rv;
    明艳谷站-普朗铁路-贸易海岸方向-rv==>|2.93|贸易海岸站-普朗铁路-贸易海岸方向-tc2;

    明艳谷站-普朗铁路-黄昏岛方向-rv2==>|2.40|帝王谷站-普朗铁路-黄昏岛方向-ev;

%% ------------------------- 赫蒙铁路-冰封港方向 -------------------------
    新赫洛堡站-赫蒙铁路-冰封港方向-nh2==>|2.90|碎叶群岛站-赫蒙铁路-冰封港方向-sti;
    碎叶群岛站-赫蒙铁路-冰封港方向-sti==>|5.58|泽地站-赫蒙铁路-冰封港方向-spi;
    泽地站-赫蒙铁路-冰封港方向-spi==>|1.97|春风平原站-赫蒙铁路-冰封港方向-sb2;
    春风平原站-赫蒙铁路-冰封港方向-sb2==>|3.29|金色平原站-赫蒙铁路-冰封港方向-gp;
    金色平原站-赫蒙铁路-冰封港方向-gp==>|1.14|精灵林地站-赫蒙铁路-冰封港方向-ew;
    精灵林地站-赫蒙铁路-冰封港方向-ew==>|1.32|秋林谷站-赫蒙铁路-冰封港方向-av;
    秋林谷站-赫蒙铁路-冰封港方向-av==>|1.76|冬泉谷站-赫蒙铁路-冰封港方向-wsv1;
    冬泉谷站-赫蒙铁路-冰封港方向-wsv1==>|1.90|烟囱山站-赫蒙铁路-冰封港方向-cm;
    烟囱山站-赫蒙铁路-冰封港方向-cm==>|2.53|霜湖谷站-赫蒙铁路-冰封港方向-fv2;
    霜湖谷站-赫蒙铁路-冰封港方向-fv2==>|3.59|冰封港站-赫蒙铁路-冰封港方向-fh;

%% ------------------------- 赫蒙铁路-新赫洛堡方向 -------------------------
    碎叶群岛站-赫蒙铁路-新赫洛堡方向-sti==>|2.90|新赫洛堡站-赫蒙铁路-新赫洛堡方向-nh2;
    泽地站-赫蒙铁路-新赫洛堡方向-spi==>|5.58|碎叶群岛站-赫蒙铁路-新赫洛堡方向-sti;
    春风平原站-赫蒙铁路-新赫洛堡方向-sb2==>|1.97|泽地站-赫蒙铁路-新赫洛堡方向-spi;
    金色平原站-赫蒙铁路-新赫洛堡方向-gp==>|3.29|春风平原站-赫蒙铁路-新赫洛堡方向-sb2;
    精灵林地站-赫蒙铁路-新赫洛堡方向-ew==>|1.14|金色平原站-赫蒙铁路-新赫洛堡方向-gp;
    秋林谷站-赫蒙铁路-新赫洛堡方向-av==>|1.32|精灵林地站-赫蒙铁路-新赫洛堡方向-ew;
    冬泉谷站-赫蒙铁路-新赫洛堡方向-wsv1==>|1.76|秋林谷站-赫蒙铁路-新赫洛堡方向-av;
    烟囱山站-赫蒙铁路-新赫洛堡方向-cm==>|1.90|冬泉谷站-赫蒙铁路-新赫洛堡方向-wsv1;
    霜湖谷站-赫蒙铁路-新赫洛堡方向-fv2==>|2.53|烟囱山站-赫蒙铁路-新赫洛堡方向-cm;
    冰封港站-赫蒙铁路-新赫洛堡方向-fh==>|3.59|霜湖谷站-赫蒙铁路-新赫洛堡方向-fv2;

%% ------------------------- 蒙德铁路-诺亚方向 -------------------------
    冬泉谷站-蒙德铁路-诺亚方向-wsv2==>|2.55|诺亚站-蒙德铁路-诺亚方向-no2;
    -蒙德铁路-诺亚方向-sfb==>|2.67|冬泉谷站-蒙德铁路-诺亚方向-wsv2;
    银光平原站-蒙德铁路-诺亚方向-sp==>|0.96|-蒙德铁路-诺亚方向-sfb;
    枫林河谷站-蒙德铁路-诺亚方向-mv==>|2.71|银光平原站-蒙德铁路-诺亚方向-sp;
    新特拉姆站-蒙德铁路-诺亚方向-nt2==>|2.23|枫林河谷站-蒙德铁路-诺亚方向-mv;
    三叉戟流域站-蒙德铁路-诺亚方向-tw==>|2.92|新特拉姆站-蒙德铁路-诺亚方向-nt2;
    东海望站-蒙德铁路-诺亚方向-eo2==>|3.10|三叉戟流域站-蒙德铁路-诺亚方向-tw;

%% ------------------------- 蒙德铁路-东海望方向 -------------------------
    诺亚站-蒙德铁路-东海望方向-no2==>|2.55|冬泉谷站-蒙德铁路-东海望方向-wsv2;
    冬泉谷站-蒙德铁路-东海望方向-wsv2==>|2.67|-蒙德铁路-东海望方向-sfb;
    -蒙德铁路-东海望方向-sfb==>|0.96|银光平原站-蒙德铁路-东海望方向-sp;
    银光平原站-蒙德铁路-东海望方向-sp==>|2.71|枫林河谷站-蒙德铁路-东海望方向-mv;
    枫林河谷站-蒙德铁路-东海望方向-mv==>|2.23|新特拉姆站-蒙德铁路-东海望方向-nt2;
    新特拉姆站-蒙德铁路-东海望方向-nt2==>|2.92|三叉戟流域站-蒙德铁路-东海望方向-tw;
    三叉戟流域站-蒙德铁路-东海望方向-tw==>|3.10|东海望站-蒙德铁路-东海望方向-eo2;

%% ------------------------- 结束乐队专线-结束乐队度假岛方向 -------------------------
    结束乐队开发区站-芙德铁路-碧玺岛方向-kz==>|0.00|-结束乐队专线-结束乐队度假岛方向-kbzx;
    -结束乐队专线-结束乐队度假岛方向-kbzx==>|2.21|结束乐队度假岛站-结束乐队专线-结束乐队度假岛方向-kri;

%% ------------------------- 结束乐队专线-结束乐队开发区方向 -------------------------
    结束乐队度假岛站-结束乐队专线-结束乐队开发区方向-kri==>|2.21|结束乐队开发区站-芙德铁路-鹅城方向-kz;

%% ------------------------- 普蒙铁路-匕首半岛方向 -------------------------
    巨龙峡湾东站-普蒙铁路-匕首半岛方向-dfe==>|4.21|巨龙峡湾站-普蒙铁路-匕首半岛方向-df2;
    巨龙峡湾站-普蒙铁路-匕首半岛方向-df2==>|3.15|雪狐森林站-普蒙铁路-匕首半岛方向-swff;
    雪狐森林站-普蒙铁路-匕首半岛方向-swff==>|1.40|-普蒙铁路-匕首半岛方向-gv;
    -普蒙铁路-匕首半岛方向-gv==>|1.60|静风林地站-普蒙铁路-匕首半岛方向-swf;
    静风林地站-普蒙铁路-匕首半岛方向-swf==>|2.31|新特拉姆站-普蒙铁路-匕首半岛方向-nt3;
    新特拉姆站-普蒙铁路-匕首半岛方向-nt3==>|2.20|南湖林地站-普蒙铁路-匕首半岛方向-sw;
    南湖林地站-普蒙铁路-匕首半岛方向-sw==>|1.82|红松丘陵站-普蒙铁路-匕首半岛方向-rh;
    红松丘陵站-普蒙铁路-匕首半岛方向-rh==>|3.20|春风平原站-普蒙铁路-匕首半岛方向-sb3;
    春风平原站-普蒙铁路-匕首半岛方向-sb3==>|4.91|海莲城站-普蒙铁路-匕首半岛方向-sc;
    海莲城站-普蒙铁路-匕首半岛方向-sc==>|2.39|-普蒙铁路-匕首半岛方向-th;
    -普蒙铁路-匕首半岛方向-th==>|3.54|匕首半岛站-普蒙铁路-匕首半岛方向-dp2;

%% ------------------------- 普蒙铁路-巨龙峡湾东方向 -------------------------
    巨龙峡湾站-普蒙铁路-巨龙峡湾东方向-df2==>|4.21|巨龙峡湾东站-普蒙铁路-巨龙峡湾东方向-dfe;
    雪狐森林站-普蒙铁路-巨龙峡湾东方向-swff==>|3.15|巨龙峡湾站-普蒙铁路-巨龙峡湾东方向-df2;
    -普蒙铁路-巨龙峡湾东方向-gv==>|1.40|雪狐森林站-普蒙铁路-巨龙峡湾东方向-swff;
    静风林地站-普蒙铁路-巨龙峡湾东方向-swf==>|1.60|-普蒙铁路-巨龙峡湾东方向-gv;
    新特拉姆站-普蒙铁路-巨龙峡湾东方向-nt3==>|2.31|静风林地站-普蒙铁路-巨龙峡湾东方向-swf;
    南湖林地站-普蒙铁路-巨龙峡湾东方向-sw==>|2.20|新特拉姆站-普蒙铁路-巨龙峡湾东方向-nt3;
    红松丘陵站-普蒙铁路-巨龙峡湾东方向-rh==>|1.82|南湖林地站-普蒙铁路-巨龙峡湾东方向-sw;
    春风平原站-普蒙铁路-巨龙峡湾东方向-sb3==>|3.20|红松丘陵站-普蒙铁路-巨龙峡湾东方向-rh;
    海莲城站-普蒙铁路-巨龙峡湾东方向-sc==>|4.91|春风平原站-普蒙铁路-巨龙峡湾东方向-sb3;
    -普蒙铁路-巨龙峡湾东方向-th==>|2.39|海莲城站-普蒙铁路-巨龙峡湾东方向-sc;
    匕首半岛站-普蒙铁路-巨龙峡湾东方向-dp2==>|3.54|-普蒙铁路-巨龙峡湾东方向-th;

%% ------------------------- 极地铁路-风雪峡湾方向 -------------------------
    巨龙峡湾东站-极地铁路-风雪峡湾方向-dfe2==>|4.95|世界边缘山脉站-极地铁路-风雪峡湾方向-em2;
    世界边缘山脉站-极地铁路-风雪峡湾方向-em2==>|3.60|东死亡之海站-极地铁路-风雪峡湾方向-esd;
    东死亡之海站-极地铁路-风雪峡湾方向-esd==>|2.06|-极地铁路-风雪峡湾方向-wsd;
    -极地铁路-风雪峡湾方向-wsd==>|2.03|冰封港站-极地铁路-风雪峡湾方向-fh2;
    冰封港站-极地铁路-风雪峡湾方向-fh2==>|6.07|-极地铁路-风雪峡湾方向-nf;
    -极地铁路-风雪峡湾方向-nf==>|2.25|风雪峡湾站-极地铁路-风雪峡湾方向-sf2;


%% ------------------------- 极地铁路-巨龙峡湾东方向 -------------------------
    风雪峡湾站-极地铁路-巨龙峡湾东方向-sf2==>|2.25|-极地铁路-巨龙峡湾东方向-nf;
    -极地铁路-巨龙峡湾东方向-nf==>|6.07|冰封港站-极地铁路-巨龙峡湾东方向-fh2;
    冰封港站-极地铁路-巨龙峡湾东方向-fh2==>|2.03|-极地铁路-巨龙峡湾东方向-wsd;
    -极地铁路-巨龙峡湾东方向-wsd==>|2.06|东死亡之海站-极地铁路-巨龙峡湾东方向-esd;
    东死亡之海站-极地铁路-巨龙峡湾东方向-esd==>|3.60|世界边缘山脉站-极地铁路-巨龙峡湾东方向-em2;
    世界边缘山脉站-极地铁路-巨龙峡湾东方向-em2==>|4.95|巨龙峡湾东站-极地铁路-巨龙峡湾东方向-dfe2;


%% ------------------------- 联络线 -------------------------
%% 芙德<-->鹅城<-->环线
    鹅城站-芙德铁路-鹅城方向-ce2-.->|4.07|诺亚站-环线铁路-外环方向-no;
    诺亚站-环线铁路-内环方向-no-.->|4.07|-/-/-celpd2fdd;
    -/-/-celpd2fdd-.->|0.00|鹅城站-芙德铁路-碧玺岛方向-ce2;
%% 丰饶台地 芙德<-->普朗
    丰饶台地西站-芙德铁路-碧玺岛方向-fpw-.->|0.00|-/-/-fpfdd2pld;
    -/-/-fpfdd2pld-.->|0.83|丰饶台地站-普朗铁路-世界边缘山脉方向-fp2;
    丰饶台地站-普朗铁路-黄昏岛方向-fp2-.->|0.00|-/-/-fpplu2fdu;
    -/-/-fpplu2fdu-.->|0.83|丰饶台地西站-芙德铁路-鹅城方向-fpw;
%% 世界树原野 环线<-->芙德
    世界树原野站-芙德铁路-碧玺岛方向-yp2-.->|0.00|-/-/-ypfdd2lpu;
    -/-/-ypfdd2lpu-.->|1.94|秋华町站-环线铁路-外环方向-ac;
    秋华町站-环线铁路-内环方向-ac-.->|1.94|-/-/-yplpd2fdu;
    -/-/-yplpd2fdu-.->|0.00|世界树原野站-芙德铁路-鹅城方向-yp2;
%% 恶土<-->环线
    天堂群峰站-环线铁路-外环方向-pp-.->|3.65|-/-/-yplp2df;
    -/-/-yplp2df-.->|0.00|恶土站-芙德铁路-鹅城方向-bl;
    -/-/-ypdf2lp-.->|3.65|天堂群峰站-环线铁路-内环方向-pp;
    恶土站-芙德铁路-碧玺岛方向-bl-.->|0.00|-/-/-ypdf2lp;
%% 春风平原 芙德<-->赫蒙
    春风平原站-赫蒙铁路-新赫洛堡方向-sb2-.->|0.00|-/-/-sbhmu2fdd;
    -/-/-sbhmu2fdd-.->|3.19|丰饶台地西站-芙德铁路-碧玺岛方向-fpw;
    丰饶台地西站-芙德铁路-鹅城方向-fpw-.->|3.19|-/-/-sbfdu2hmd;
    -/-/-sbfdu2hmd-.->|0.00|春风平原站-赫蒙铁路-冰封港方向-sb2;

    春风平原站-芙德铁路-碧玺岛方向-sb-.->|0.00|-/-/-sbdf2hm;
    -/-/-sbdf2hm-.->|1.97|泽地站-赫蒙铁路-新赫洛堡方向-spi;
    泽地站-赫蒙铁路-冰封港方向-spi-.->|1.97|-/-/-sbhm2df;
    -/-/-sbhm2df-.->|0.00|春风平原站-芙德铁路-鹅城方向-sb;
%% 普朗<-->黄昏岛<-->环线
    黄昏岛站-普朗铁路-黄昏岛方向-ti2-.->|1.88|匕首半岛站-环线铁路-外环方向-dp;
    匕首半岛站-环线铁路-内环方向-dp-.->|1.88|-/-/-tilpd2pld;
    -/-/-tilpd2pld-.->|0.00|黄昏岛站-普朗铁路-世界边缘山脉方向-ti2;
%% 蒙德<-->诺亚<-->环线
    风雪峡湾站-环线铁路-内环方向-sf-.->|0.00|-/-/-nolpd2mdd;
    -/-/-nolpd2mdd-.->|3.05|诺亚站-蒙德铁路-东海望方向-no2;
    诺亚站-蒙德铁路-诺亚方向-no2-.->|3.05|风雪峡湾站-环线铁路-外环方向-sf;
%% 冬泉谷 蒙德<-->赫蒙
    秋林谷站-赫蒙铁路-冰封港方向-av-.->|0.00|-/-/-wsvhmd2mdu;
    -/-/-wsvhmd2mdu-.->|1.76|冬泉谷站-蒙德铁路-诺亚方向-wsv2;
    冬泉谷站-蒙德铁路-东海望方向-wsv2-.->|0.00|-/-/-wsvmdd2hmu;
-/-/-wsvmdd2hmu-.->|1.76|秋林谷站-赫蒙铁路-新赫洛堡方向-av;

-蒙德铁路-诺亚方向-sfb-.->|2.67|-/-/-wsvmdu2hmd;
-/-/-wsvmdu2hmd-.->|0.00|冬泉谷站-赫蒙铁路-冰封港方向-wsv1;
冬泉谷站-赫蒙铁路-新赫洛堡方向-wsv1-.->|2.67|-/-/-wsvhmu2mdd;
-/-/-wsvhmu2mdd-.->|0.00|-蒙德铁路-东海望方向-sfb;
%% 冬泉谷南 蒙德<-->赫蒙
-蒙德铁路-诺亚方向-sfb-.->|0.00|-/-/-wsvmd2hm;
-/-/-wsvmd2hm-.->|3.19|秋林谷站-赫蒙铁路-新赫洛堡方向-av;
秋林谷站-赫蒙铁路-冰封港方向-av-.->|3.19|-/-/-wsvhm2md;
-/-/-wsvhm2md-.->|0.00|-蒙德铁路-东海望方向-sfb;
%% 芙德<-->森海环线<-->赫蒙
春风平原站-芙德铁路-碧玺岛方向-sb-.->|0.00|-/-/-sbdf2shlp;
-/-/-sbdf2shlp-.->|4.10|金色平原站-赫蒙铁路-冰封港方向-gp;
金色平原站-赫蒙铁路-新赫洛堡方向-gp-.->|4.10|-/-/-sbhm2shlp;
-/-/-sbhm2shlp-.->|0.00|春风平原站-芙德铁路-鹅城方向-sb;
%% 芙德<--->普朗
丰饶台地北站-普朗铁路-黄昏岛方向-fpn-.->|0.00|-/-/-fpnpl2df;
-/-/-fpnpl2df-.->|3.35|德芙站-芙德铁路-碧玺岛方向-do;
德芙站-芙德铁路-鹅城方向-do-.->|3.35|-/-/-fpndf2pl;
-/-/-fpndf2pl-.->|0.00|丰饶台地北站-普朗铁路-世界边缘山脉方向-fpn;
%% 永望堡 普朗<-->环线
-环线铁路-外环方向-sv-.->|0.00|-/-/-eflp2pl;
-/-/-eflp2pl-.->|3.58|永望堡站-普朗铁路-黄昏岛方向-ef2;
永望堡站-普朗铁路-世界边缘山脉方向-ef2-.->|3.58|-/-/-efpl2lp;
-/-/-efpl2lp-.->|0.00|-环线铁路-内环方向-sv;
%% 霜湖谷 赫蒙<-->环线
烟囱山站-赫蒙铁路-冰封港方向-cm-.->|0.00|-/-/-fvhmd2lpu;
-/-/-fvhmd2lpu-.->|2.53|霜湖谷站-环线铁路-外环方向-fv1;
霜湖谷站-环线铁路-内环方向-fv1-.->|0.00|-/-/-fvlpd2hmu;
-/-/-fvlpd2hmu-.->|2.53|烟囱山站-赫蒙铁路-新赫洛堡方向-cm;
%% 新特拉姆南 普朗<-->蒙德
枫林河谷站-蒙德铁路-东海望方向-mv-.->|4.24|-/-/-ntmdd2plu;
-/-/-ntmdd2plu-.->|0.00|丰饶台地北站-普朗铁路-黄昏岛方向-fpn;
丰饶台地北站-普朗铁路-世界边缘山脉方向-fpn-.->|0.00|-/-/-ntpld2mdu;
-/-/-ntpld2mdu-.->|4.24|枫林河谷站-蒙德铁路-诺亚方向-mv;
%% 东海望塔桥联络线
东海望站-蒙德铁路-东海望方向-eo2-.->|2.89|-环线铁路-内环方向-ff;
-环线铁路-外环方向-ff-.->|2.89|-/-/-eolpu2mdu;
-/-/-eolpu2mdu-.->|0.00|东海望站-蒙德铁路-诺亚方向-eo2;
%% 新特拉姆东 普朗<-->蒙德
三叉戟流域站-蒙德铁路-诺亚方向-tw-.->|3.45|-/-/-ntmdu2pld;
-/-/-ntmdu2pld-.->|0.00|-普朗铁路-世界边缘山脉方向-bt;
-普朗铁路-黄昏岛方向-bt-.->|0.00|-/-/-ntplu2mdd;
-/-/-ntplu2mdd-.->|3.45|三叉戟流域站-蒙德铁路-东海望方向-tw;
%% 明艳谷 普朗<-->普朗黄昏岛联络线
明艳谷站-普朗铁路-世界边缘山脉方向-rv-.->|0.00|-/-/-pld2plz;
-/-/-pld2plz-.->|2.40|帝王谷站-普朗铁路-黄昏岛方向-ev;
%% 贸易海岸 普朗<-->环线
贸易海岸站-环线铁路-外环方向-tc-.->|2.93|-/-/-tclpu2plz;
-/-/-tclpu2plz-.->|0.00|明艳谷站-普朗铁路-世界边缘山脉方向-rv;
明艳谷站-普朗铁路-贸易海岸方向-rv-.->|2.93|-/-/-tcplz2lpd;
-/-/-tcplz2lpd-.->|0.00|贸易海岸站-环线铁路-内环方向-tc;
%% 芙德支线 <--> 结束乐队专线
赤脊湾站-芙德铁路-大绿龙岛方向-rb2-.->|0.00|-/-/-rbfdzu2kbzxu;
-/-/-rbfdzu2kbzxu-.->|1.79|结束乐队度假岛站-结束乐队专线-结束乐队度假岛方向-kri;
结束乐队度假岛站-结束乐队专线-结束乐队开发区方向-kri-.->|1.79|-/-/-rbkbzxd2fdzd;
-/-/-rbkbzxd2fdzd-.->|0.00|赤脊湾站-芙德铁路-碧玺岛方向-rb;
%% 新特拉姆站西 蒙德<-->普蒙
新特拉姆站-蒙德铁路-诺亚方向-nt2-.->|0.00|-/-/-ntmdu2pmu;
-/-/-ntmdu2pmu-.->|2.20|南湖林地站-普蒙铁路-匕首半岛方向-sw;
南湖林地站-普蒙铁路-巨龙峡湾东方向-sw-.->|2.20|-/-/-ntpmd2mdd;
-/-/-ntpmd2mdd-.->|0.00|新特拉姆站-蒙德铁路-东海望方向-nt2;
%% 新特拉姆站西南 蒙德<-->普蒙
红松丘陵站-普蒙铁路-巨龙峡湾东方向-rh-.->|4.47|-/-/-ntpmd2mdu;
-/-/-ntpmd2mdu-.->|0.00|枫林河谷站-蒙德铁路-诺亚方向-mv;
-/-/-ntmdd2plu-.->|0.00|-/-/-ntmdd2pmu;
-/-/-ntmdd2pmu-.->|4.47|红松丘陵站-普蒙铁路-匕首半岛方向-rh;
%% 新特拉姆站东 蒙德/普蒙<-->普朗
新特拉姆站-蒙德铁路-东海望方向-nt2-.->|0.00|-/-/-ntmdd2pld;
-/-/-ntmdd2pld-.->|1.75|-普朗铁路-世界边缘山脉方向-bt;
新特拉姆站-普蒙铁路-巨龙峡湾东方向-nt3-.->|0.00|-/-/-ntpmd2pld;
-/-/-ntpmd2pld-.->|1.75|-普朗铁路-世界边缘山脉方向-bt;

-普朗铁路-黄昏岛方向-bt-.->|1.75|-/-/-ntpld2mdupmu;
-/-/-ntpld2mdupmu-.->|0.00|-/-/-ntmdupmu2mdu;
-/-/-ntmdupmu2mdu-.->|0.00|新特拉姆站-蒙德铁路-诺亚方向-nt2;
-/-/-ntpld2mdupmu-.->|1.75|新特拉姆站-普蒙铁路-匕首半岛方向-nt3;
%% 新特拉姆站东 蒙德<-->普蒙
新特拉姆站-蒙德铁路-东海望方向-nt2-.->|0.00|-/-/-ntmdd2pmd;
-/-/-ntmdd2pmd-.->|2.31|静风林地站-普蒙铁路-巨龙峡湾东方向-swf;
静风林地站-普蒙铁路-匕首半岛方向-swf-.->|2.31|-/-/-ntpmu2mdu;
-/-/-ntpmu2mdu-.->|0.00|新特拉姆站-蒙德铁路-诺亚方向-nt2;
%% 春风平原南 普蒙<-->赫蒙
春风平原站-普蒙铁路-匕首半岛方向-sb3-.->|0.00|-/-/-sbpmu2hmu;
-/-/-sbpmu2hmu-.->|6.13|碎叶群岛站-赫蒙铁路-新赫洛堡方向-sti;
碎叶群岛站-赫蒙铁路-冰封港方向-sti-.->|6.13|-/-/-sbhmd2pmd;
-/-/-sbhmd2pmd-.->|0.00|春风平原站-普蒙铁路-巨龙峡湾东方向-sb3;
%% 碧玺岛 环线<-->芙德
秋华町站-环线铁路-内环方向-ac-.->|0.00|-/-/-bilpd2fdd;
-/-/-bilpd2fdd-.->|4.35|碧玺岛站-芙德铁路-碧玺岛方向-bi;
碧玺岛站-芙德铁路-鹅城方向-bi-.->|4.35|-/-/-bifdu2lpu;
-/-/-bifdu2lpu-.->|0.00|秋华町站-环线铁路-外环方向-ac;
%% 巨龙峡湾 环线<-->普蒙
-环线铁路-内环方向-ff-.->|3.57|-/-/-dflpd2pmd;
-/-/-dflpd2pmd-.->|0.00|巨龙峡湾站-普蒙铁路-巨龙峡湾东方向-df2;
巨龙峡湾站-普蒙铁路-匕首半岛方向-df2-.->|0.00|-/-/-dfpmu2lpu;
-/-/-dfpmu2lpu-.->|3.57|-环线铁路-外环方向-ff;
%% 冰封港 极地<-->赫蒙
冰封港站-极地铁路-巨龙峡湾东方向-fh2-.->|0.00|-/-/-fhjdd2hmu;
-/-/-fhjdd2hmu-.->|3.59|霜湖谷站-赫蒙铁路-新赫洛堡方向-fv2;
霜湖谷站-赫蒙铁路-冰封港方向-fv2-.->|3.59|-/-/-fhhmd2jdu;
-/-/-fhhmd2jdu-.->|0.00|冰封港站-极地铁路-风雪峡湾方向-fh2;
%% 巨龙峡湾 极地<-->普蒙
巨龙峡湾站-普蒙铁路-巨龙峡湾东方向-df2-.->|0.00|-/-/-empmd2jdu;
-/-/-empmd2jdu-.->|2.90|世界边缘山脉站-极地铁路-风雪峡湾方向-em2;
世界边缘山脉站-极地铁路-巨龙峡湾东方向-em2-.->|2.90|-/-/-emjdd2pmu;
-/-/-emjdd2pmu-.->|0.00|巨龙峡湾站-普蒙铁路-匕首半岛方向-df2;
%% 赤脊湾 主线<-->支线/结束乐队专线
赤脊湾站-芙德铁路-鹅城方向-rb-.->|0.00|-/-/-rbfdu2fdzu1;
-/-/-rbfdu2fdzu1-.->|0.00|-芙德铁路-龙爪半岛方向-rbfdu2fdzu2;
-/-/-rbfdu2fdzu1-.->|0.00|-/-/-rbfdzu2kbzxu;
-/-/-rbfdu2fdzu1-.->|0.00|龙颚岛站-芙德铁路-大绿龙岛方向-dji;



classDef 环线铁路 fill:#FF5555,stroke:#333,stroke-width:2px,color:#000000;
classDef 芙德铁路 fill:#80DB00,stroke:#333,stroke-width:2px,color:#000000;
classDef 普朗铁路 fill:#FF9823,stroke:#333,stroke-width:2px,color:#000000;
classDef 赫蒙铁路 fill:#0000DD,stroke:#333,stroke-width:2px,color:#000000;
classDef 蒙德铁路 fill:#55FFFF,stroke:#333,stroke-width:2px,color:#000000;
classDef 结束乐队专线 fill:#AA0000,stroke:#333,stroke-width:2px,color:#000000;
classDef 普蒙铁路 fill:#FF55FF,stroke:#333,stroke-width:2px,color:#000000;
classDef 极地铁路 fill:#00AAAA,stroke:#333,stroke-width:2px,color:#000000;
class 天堂群峰站-环线铁路-外环方向-pp,天堂群峰站-环线铁路-内环方向-pp,苍原岭站-环线铁路-外环方向-vr,苍原岭站-环线铁路-内环方向-vr,霜湖谷站-环线铁路-内环方向-fv1,霜湖谷站-环线铁路-外环方向-fv1,风雪峡湾站-环线铁路-外环方向-sf,风雪峡湾站-环线铁路-内环方向-sf,冬幕公园站-环线铁路-内环方向-wp,冬幕公园站-环线铁路-外环方向-wp,东海望站-环线铁路-内环方向-eo1,东海望站-环线铁路-外环方向-eo1,巨龙峡湾站-环线铁路-内环方向-df,巨龙峡湾站-环线铁路-外环方向-df,永望堡站-环线铁路-内环方向-ef1,永望堡站-环线铁路-外环方向-ef1,匕首半岛站-环线铁路-外环方向-dp,贸易海岸站-环线铁路-外环方向-tc,龙爪半岛站-环线铁路-外环方向-dcp,翡翠岛站-环线铁路-外环方向-ei,秋华町站-环线铁路-外环方向-ac,鹅城站-环线铁路-外环方向-ce,诺亚站-环线铁路-外环方向-no,西州湾站-环线铁路-外环方向-xzw,黄昏岛站-环线铁路-外环方向-ti,银月岛站-环线铁路-外环方向-si,长岛站-环线铁路-外环方向-li,新赫洛堡站-环线铁路-外环方向-nh,大绿龙岛站-环线铁路-外环方向-ggi,银月岛站-环线铁路-内环方向-si,翡翠岛站-环线铁路-内环方向-ei,长岛站-环线铁路-内环方向-li,西州湾站-环线铁路-内环方向-xzw,秋华町站-环线铁路-内环方向-ac,匕首半岛站-环线铁路-内环方向-dp,贸易海岸站-环线铁路-内环方向-tc,鹅城站-环线铁路-内环方向-ce,诺亚站-环线铁路-内环方向-no,龙爪半岛站-环线铁路-内环方向-dcp,黄昏岛站-环线铁路-内环方向-ti,新赫洛堡站-环线铁路-内环方向-nh,大绿龙岛站-环线铁路-内环方向-ggi,世界树原野站-环线铁路-内环方向-yp1,世界树原野站-环线铁路-外环方向-yp1 环线铁路;
class 碧玺岛站-芙德铁路-碧玺岛方向-bi,碧玺岛站-芙德铁路-鹅城方向-bi,赤脊湾站-芙德铁路-龙爪半岛方向-rb3,温泉度假村站-芙德铁路-龙爪半岛方向-tsr,温泉度假村站-芙德铁路-碧玺岛方向-tsr,赤脊湾站-芙德铁路-大绿龙岛方向-rb2,龙颚岛站-芙德铁路-大绿龙岛方向-dji,龙颚岛站-芙德铁路-碧玺岛方向-dji,结束乐队开发区站-芙德铁路-鹅城方向-kz,结束乐队开发区站-芙德铁路-碧玺岛方向-kz,德芙站-芙德铁路-鹅城方向-do,暖风河谷站-芙德铁路-鹅城方向-wv,赤脊湾站-芙德铁路-鹅城方向-rb,春风平原站-芙德铁路-鹅城方向-sb,丰饶台地西站-芙德铁路-碧玺岛方向-fpw,春风平原站-芙德铁路-碧玺岛方向-sb,暖风河谷站-芙德铁路-碧玺岛方向-wv,丰饶台地站-芙德铁路-鹅城方向-fp1,丰饶台地站-芙德铁路-碧玺岛方向-fp1,鹅城站-芙德铁路-鹅城方向-ce2,丰饶台地西站-芙德铁路-鹅城方向-fpw,德芙站-芙德铁路-碧玺岛方向-do,赤脊湾站-芙德铁路-碧玺岛方向-rb,鹅城站-芙德铁路-碧玺岛方向-ce2,恶土站-芙德铁路-碧玺岛方向-bl,世界树原野站-芙德铁路-碧玺岛方向-yp2,恶土站-芙德铁路-鹅城方向-bl,世界树原野站-芙德铁路-鹅城方向-yp2 芙德铁路;
class 星陨森林站-普朗铁路-世界边缘山脉方向-sff,星陨森林站-普朗铁路-黄昏岛方向-sff,红色裂土站-普朗铁路-世界边缘山脉方向-rr,红色裂土站-普朗铁路-黄昏岛方向-rr,不可视境界站-普朗铁路-世界边缘山脉方向-bw,不可视境界站-普朗铁路-黄昏岛方向-bw,世界边缘山脉站-普朗铁路-黄昏岛方向-em,世界边缘山脉站-普朗铁路-世界边缘山脉方向-em,金合欢高原站-普朗铁路-世界边缘山脉方向-ap,金合欢高原站-普朗铁路-黄昏岛方向-ap,贸易海岸站-普朗铁路-贸易海岸方向-tc2,贸易海岸站-普朗铁路-世界边缘山脉方向-tc2,明艳谷站-普朗铁路-贸易海岸方向-rv,明艳谷站-普朗铁路-黄昏岛方向-rv2,明艳谷站-普朗铁路-世界边缘山脉方向-rv,冰晶湖站-普朗铁路-黄昏岛方向-fcl,冰晶湖站-普朗铁路-世界边缘山脉方向-fcl,永望堡站-普朗铁路-世界边缘山脉方向-ef2,永望堡站-普朗铁路-黄昏岛方向-ef2,黄昏岛站-普朗铁路-黄昏岛方向-ti2,帝王谷站-普朗铁路-黄昏岛方向-ev,帝王谷站-普朗铁路-世界边缘山脉方向-ev,黄昏岛站-普朗铁路-世界边缘山脉方向-ti2,丰饶台地北站-普朗铁路-世界边缘山脉方向-fpn,丰饶台地北站-普朗铁路-黄昏岛方向-fpn,丰饶台地站-普朗铁路-世界边缘山脉方向-fp2,新特拉姆站-普朗铁路-世界边缘山脉方向-nt,新特拉姆站-普朗铁路-黄昏岛方向-nt,丰饶台地站-普朗铁路-黄昏岛方向-fp2 普朗铁路;
class 冰封港站-赫蒙铁路-冰封港方向-fh,冰封港站-赫蒙铁路-新赫洛堡方向-fh,碎叶群岛站-赫蒙铁路-冰封港方向-sti,碎叶群岛站-赫蒙铁路-新赫洛堡方向-sti,精灵林地站-赫蒙铁路-新赫洛堡方向-ew,精灵林地站-赫蒙铁路-冰封港方向-ew,烟囱山站-赫蒙铁路-新赫洛堡方向-cm,烟囱山站-赫蒙铁路-冰封港方向-cm,霜湖谷站-赫蒙铁路-新赫洛堡方向-fv2,霜湖谷站-赫蒙铁路-冰封港方向-fv2,秋林谷站-赫蒙铁路-冰封港方向-av,秋林谷站-赫蒙铁路-新赫洛堡方向-av,冬泉谷站-赫蒙铁路-冰封港方向-wsv1,冬泉谷站-赫蒙铁路-新赫洛堡方向-wsv1,泽地站-赫蒙铁路-新赫洛堡方向-spi,泽地站-赫蒙铁路-冰封港方向-spi,金色平原站-赫蒙铁路-新赫洛堡方向-gp,金色平原站-赫蒙铁路-冰封港方向-gp,春风平原站-赫蒙铁路-新赫洛堡方向-sb2,新赫洛堡站-赫蒙铁路-新赫洛堡方向-nh2,新赫洛堡站-赫蒙铁路-冰封港方向-nh2,春风平原站-赫蒙铁路-冰封港方向-sb2 赫蒙铁路;
class 枫林河谷站-蒙德铁路-东海望方向-mv,枫林河谷站-蒙德铁路-诺亚方向-mv,东海望站-蒙德铁路-诺亚方向-eo2,东海望站-蒙德铁路-东海望方向-eo2,三叉戟流域站-蒙德铁路-诺亚方向-tw,三叉戟流域站-蒙德铁路-东海望方向-tw,新特拉姆站-蒙德铁路-诺亚方向-nt2,新特拉姆站-蒙德铁路-东海望方向-nt2,银光平原站-蒙德铁路-诺亚方向-sp,银光平原站-蒙德铁路-东海望方向-sp,诺亚站-蒙德铁路-东海望方向-no2,冬泉谷站-蒙德铁路-东海望方向-wsv2,冬泉谷站-蒙德铁路-诺亚方向-wsv2,诺亚站-蒙德铁路-诺亚方向-no2 蒙德铁路
class 结束乐队度假岛站-结束乐队专线-结束乐队开发区方向-kri,结束乐队度假岛站-结束乐队专线-结束乐队度假岛方向-kri 结束乐队专线;
class 海莲城站-普蒙铁路-匕首半岛方向-sc,海莲城站-普蒙铁路-巨龙峡湾东方向-sc,-普蒙铁路-匕首半岛方向-th,匕首半岛站-普蒙铁路-匕首半岛方向-dp2,-普蒙铁路-巨龙峡湾东方向-th,匕首半岛站-普蒙铁路-巨龙峡湾东方向-dp2,雪狐森林站-普蒙铁路-匕首半岛方向-swff,-普蒙铁路-匕首半岛方向-gv,静风林地站-普蒙铁路-匕首半岛方向-swf,雪狐森林站-普蒙铁路-巨龙峡湾东方向-swff,-普蒙铁路-巨龙峡湾东方向-gv,静风林地站-普蒙铁路-巨龙峡湾东方向-swf,巨龙峡湾东站-普蒙铁路-巨龙峡湾东方向-dfe,巨龙峡湾站-普蒙铁路-巨龙峡湾东方向-df2,巨龙峡湾站-普蒙铁路-匕首半岛方向-df2,巨龙峡湾东站-普蒙铁路-匕首半岛方向-dfe,春风平原站-普蒙铁路-巨龙峡湾东方向-sb3,春风平原站-普蒙铁路-匕首半岛方向-sb3,红松丘陵站-普蒙铁路-巨龙峡湾东方向-rh,红松丘陵站-普蒙铁路-匕首半岛方向-rh,南湖林地站-普蒙铁路-巨龙峡湾东方向-sw,南湖林地站-普蒙铁路-匕首半岛方向-sw,新特拉姆站-普蒙铁路-巨龙峡湾东方向-nt3,新特拉姆站-普蒙铁路-匕首半岛方向-nt3 普蒙铁路;
class 风雪峡湾站-极地铁路-风雪峡湾方向-sf2,-极地铁路-风雪峡湾方向-nf,-极地铁路-巨龙峡湾东方向-nf,风雪峡湾站-极地铁路-巨龙峡湾东方向-sf2,东死亡之海站-极地铁路-巨龙峡湾东方向-esd,-极地铁路-巨龙峡湾东方向-wsd,冰封港站-极地铁路-巨龙峡湾东方向-fh2,冰封港站-极地铁路-风雪峡湾方向-fh2,-极地铁路-风雪峡湾方向-wsd,东死亡之海站-极地铁路-风雪峡湾方向-esd,巨龙峡湾东站-极地铁路-风雪峡湾方向-dfe2,世界边缘山脉站-极地铁路-风雪峡湾方向-em2,世界边缘山脉站-极地铁路-巨龙峡湾东方向-em2,巨龙峡湾东站-极地铁路-巨龙峡湾东方向-dfe2 极地铁路;
